name: run-tests
on: [pull_request]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/defend
      OAUTHLIB_INSECURE_TRANSPORT: 1
      RUNNING_LOCALLY: 0
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'
      - name: Install python packages
        run: pip install -r defend_data_capture/requirements.txt
      - name: Run unit tests
        run: which pip && python --version && pytest defend_data_capture --collect-only
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node modules
        run: npm install
      - name: Run webpack
        run: nohup npm run dev &
      - name: Bring up db container
        run: docker-compose -f docker-compose.yaml up -d

      - name: Run functional tests
        run: bash run_functional_tests.sh
